# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
plugins: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://allyrv.github.io/ 
baseurl: /sustain/
title: Alyssa Vargas
author: Alyssa Vargas
description: Personal blog and resume
avatar: profile.png
email: allyrvargas@gmail.com
github: allyrv
instagram: allyyvv
linkedin: alyssarvargas
#stackoverflow: username   #e.g: users/2735833/proton1h1
#Comment out if you don't want disqus
#disqus: username
#google_analytics: 


# needed for travis-ci build
exclude: [vendor]
